// refactor/code-polish-updates
const ERROR_CODES = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  RESOURCE_EXISTS: "RESOURCE_EXISTS",
  OPERATION_FAILED: "OPERATION_FAILED",
  SERVER_ERROR: "SERVER_ERROR",
  INVALID_ID: "INVALID_ID",
  DUPLICATE_FIELD: "DUPLICATE_FIELD",
  INVALID_TOKEN: "INVALID_TOKEN",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  RATE_LIMITED: "RATE_LIMITED",
  ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  ACCOUNT_INACTIVE: "ACCOUNT_INACTIVE",
  ACCOUNT_NOT_VERIFIED: "ACCOUNT_NOT_VERIFIED",
  UNAUTHORIZED_ACCESS: "UNAUTHORIZED_ACCESS",
};

export default ERROR_CODES;
