const ERROR_CODES = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  RESOURCE_EXISTS: "RESOURCE_EXISTS",
  OPERATION_FAILED: "OPERATION_FAILED",
  SERVER_ERROR: "SERVER_ERROR",
  INVALID_ID: "INVALID_ID",
  DUPLICATE_FIELD: "DUPLICATE_FIELD",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  INVALID_TOKEN: "INVALID_TOKEN",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  RATE_LIMITED: "RATE_LIMITED",
  // Add more generic codes as needed
};

export default ERROR_CODES;
