// backend/constants/ErrorCodes.js
const ERROR_CODES = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  RESOURCE_EXISTS: "RESOURCE_EXISTS",
  OPERATION_FAILED: "OPERATION_FAILED",
  SERVER_ERROR: "SERVER_ERROR",
  INVALID_ID: "INVALID_ID",
  DUPLICATE_FIELD: "DUPLICATE_FIELD",
  INVALID_TOKEN: "INVALID_TOKEN",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  RATE_LIMITED: "RATE_LIMITED",
  ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",
  // More generic codes here
};

export default ERROR_CODES;
